#!/bin/bash
echo "" > loopcheck.t
for f in tests/*
do
 echo "======================================Processing $f======================================" >> loopcheck.t
 ./mylang < $f >> loopcheck.t
done

